% Compute power spectrum

% Generated by MATLAB(R) 9.10 and Signal Processing Toolbox 8.6.
% Generated on: 14-Jul-2022 21:08:07

% Parameters
frequencyLimits = [0 1]*pi; % Normalized frequency (rad/sample)

%%
% Index into signal time region of interest
timeLimits = [279053 279729]; % samples
FIT101filtered_ROI = FIT101filtered(:);
FIT101filtered_ROI = FIT101filtered_ROI(timeLimits(1):timeLimits(2));

% Compute spectral estimate
% Run the function call below without output arguments to plot the results
[PFIT101filtered_ROI, FFIT101filtered_ROI] = pspectrum(FIT101filtered_ROI, ...
    'FrequencyLimits',frequencyLimits);
ax = gca; ax.FontSize = 14;